---
- name: deploying kerberos packaged
  hosts: all
  vars: 
   master_nodes: testNode
   follower_nodes: kafkaNodes
  vars_prompt:
   name: masterPass
   prompt: enter password for master
  roles:
   - install_krb
   - startKrb
