---
- name: docker installation started  
  hosts: worker
  tasks:
    - name: update OS
      yum: 
        name: "*"
        state: latest 
    - name:  installing docker repo
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - name: installing packages
      yum: 
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils 
        - device-mapper-persistent-data 
        - lvm2
        - containerd.io-1.2.13 
        - docker-ce-19.03.11 
        - docker-ce-cli-19.03.11    
    - name: create dir
      file: 
        path: "{{ item }}"
        state: directory 
      loop:
        - /etc/systemd/system/docker.service.d
        - /etc/docker

    - name: creating daemon.json 
      copy: 
        dest: "/etc/docker/daemon.json"
        content: |
           {
             "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
             "log-opts": {
             "max-size": "100m"
               },
            "storage-driver": "overlay2",
            "storage-opts": [
             "overlay2.override_kernel_check=true"
                ]
               }
      notify: 
        - Start and enable docker

  handlers:
    - name: Start and enable docker
      service: 
        name: docker
        state: started
        enabled: yes
